apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc117-service-registry-deployment
  labels:
    type: registry
    name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-registry-label
    spec:
      containers:
      - name: service-registry-container
        image: ghcr.io/pranjal-mukherjee/bootcamp117-backend-service-registry:v8
        ports:
        - containerPort: 8761
      imagePullSecrets: 
      - name: ghcr-secret
  selector:
    matchLabels:
      app: service-registry-label
