server:
  port: 9002

spring:
  application:
    name: BUSINESS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/pocket_pay
    username: root
    password: Test@1234
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost